### ISSUE TITLE
C bit not set for 8

### ISSUE THREAD

**Issue by mattvenn** [maehw/wokwi-lookup-table-generator#9]
https://github.com/maehw/wokwi-lookup-table-generator/blob/2b20f96304389fc30564869f93c17079e7d50afa/demos/bcd_7segment_lut.logic.json#L8

**Comment by maehw** [comment]
Thanks @mattvenn. Fixed. I was even wondering for a short moment when I saw the simulation running back then.
I'll try to repair it in the two linked wokwi designs, too.
